name: Docker Build Main and Deploy to Testing

on:
  workflow_run:
    workflows: [ 'Run Tests' ]
    branches: [ main ]
    types: [ completed ]

jobs:
  build-unstable:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.sha }}
      dockerfile: Dockerfile
    secrets: inherit

  deploy-testing:
    needs: build-unstable
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - name: Deploy to legacy testing
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ${{ needs.build-unstable.outputs.image }}
        cluster_ca: ${{ secrets.HATCHER_CLUSTER_CA }}
        cluster_server: https://hatcher.kubernetes.lib.umich.edu
        namespace_token: ${{ secrets.HATCHER_TOKEN }}
        namespace: ${{ secrets.NAMESPACE }}

  deploy-image:
    needs: build-unstable
    name: Deploy to workshop
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ${{ needs.build-unstable.outputs.image }}
      file: environments/alma-events/workshop/web-image.txt
      CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_APP_ID }}
      CONFIG_REPO_RW_INSTALL_ID: ${{ vars.CONFIG_REPO_RW_INSTALL_ID }}
      CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
    secrets: inherit
