name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release
        required: true

env:
  IMAGE_NAME: alma-webhook
  NAMESPACE: alma-utilities
  CLUSTER_TOKEN: ${{ secrets.HATCHER_PRODUCTION_TOKEN }}
  TAG: ${{ github.event.inputs.tag }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clone latest repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Check that the tag exists
      run: docker manifest inspect ghcr.io/mlibrary/$IMAGE_NAME:$TAG > /dev/null
    - uses: azure/setup-kubectl@v1
    - name: Authenticate with kubernetes
      run: |
        mkdir -p ${HOME}/.kube/certs/cluster
        echo ${{ secrets.HATCHER_CLUSTER_CA }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
        kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server=https://hatcher.kubernetes.lib.umich.edu
        kubectl config set-credentials default --token=`echo ${{ secrets.HATCHER_PRODUCTION_TOKEN }} | base64 -d`
        kubectl config set-context default --cluster=cluster --user=default --namespace=$NAMESPACE
        kubectl config use-context default
    - name: Manual Deploy
      run: kubectl set image deployment web web=ghcr.io/mlibrary/$IMAGE_NAME:$TAG
