name: Manual Deploy to Testing

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true


jobs:
  build-unstable:
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: Dockerfile
    secrets: inherit

  deploy-testing:
    needs: build-unstable
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - name: Deploy to Testing
      uses: mlibrary/deploy-to-kubernetes@v3
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ${{ needs.build-unstable.outputs.image }}
        cluster_ca: ${{ secrets.HATCHER_CLUSTER_CA }}
        cluster_server: https://hatcher.kubernetes.lib.umich.edu
        namespace_token: ${{ secrets.HATCHER_TOKEN }}
        namespace: ${{ secrets.NAMESPACE }}

