name: Manual Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true

jobs:
  build-production:
    name: Build production ${{ github.event.inputs.tag }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@v1
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.inputs.tag }}
      dockerfile: Dockerfile
    secrets: inherit

  deploy-aim-image:
    needs: build-production
    name: Deploy to aim-production
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      environment: aim
      image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}:${{ github.event.inputs.tag }}
      file: environments/alma-events/production/web-image.txt
    secrets: inherit


  deploy-search-image:
    needs: build-production
    name: Deploy to search-production
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      environment: search
      image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}:${{ github.event.inputs.tag }}
      file: environments/alma-events/production/web-image.txt
    secrets: inherit
