name: Run Tests

on: push

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache ruby gems
        uses: actions/cache@v2
        env:
          cache-name: ruby-gems
        with:
          path: .gems
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: make coverage directory
        run: mkdir -m777 coverage 
      - name: list files with permissions
        run: ls -al
      - name: Set up tests
        run: |
          docker-compose build
          docker-compose run web bundle install

      - name: Run tests
        run: docker-compose run web bundle exec rspec

